version: '3.3'

services:
  work_and_travel_core:
    container_name: debian-core
    image: debian/core
    restart: always
    build:
      dockerfile: ./Docker/Io/Dockerfile
      context: .
    working_dir: /Application
    volumes:
      - .:/Application
    command: ['/usr/bin/init']
    ports:
      - "2222:80"
    networks:
      - r3m-network
networks:
  r3m-network:
    driver: bridge
